### ISSUE TITLE
v1.1

### ISSUE THREAD

**Issue by vladdeSV** [vladdeSV/vscode-klog#21]
I am planning to release v1.1 soon. The main feature of this release is the addition of a language server, which can communicate with `klog` (>=2.3). A working version has been available since May, but I did not feel comfortable releasing it until now.

There are some caveats still, to name a few:
- LSP must be enabled in settings, and set the path for the `klog` executable
- file must be saved for LSP to work (unsure why)
- only tested on Windows so far

RC1: https://public.vladde.net/vscode-klog-1.1.0-rc.1.vsix

Installation: In *VS Code*, go the the "Extension" page, press the three dots in the top right of its panel, "Install from VSIX…"

@jotaen Would you mind testing the extension in VS Code and give it a spin? Also, which OS are you using?

**Comment by jotaen** [comment]
Oh cool, I might play around with this and write a Sublime plugin based on it at some point… 👀 

I’ll try the v1.1 out and take a look, probably on the weekend or so. Will let you know then!

I’m on macOS.

**Comment by jotaen** [comment]
I’ve tested today and it generally seems to work fine 🎉  Cool that it works out-of-the-box and in addition to the syntax highlighting.

Strange that it doesn’t work for unsaved files – it’s the same for me. But I think it’s not a big deal. Question: Why did you make the default to be “on save” and not “on edit”? I personally would always use the latter.

One thought that I had was that now that there is both syntax highlighting **and** an LSP, the red highlighting for malformed entries can become inconsistent with what the LSP reports. Both below entries are malformed, both are underlined, but the first is white and the second is red.

<img width="334" alt="Screenshot 2021-08-16 at 18 38 58" src="https://user-images.githubusercontent.com/3618384/129598850-ce7b90fc-11c2-402b-a3a8-ed568d16b220.png">

I had troubles when testing bigger files. For a large file with a lot of errors, the extension just “capped” the errors at some point.

<img width="386" alt="Screenshot 2021-08-16 at 18 25 07" src="https://user-images.githubusercontent.com/3618384/129597307-0a6374e2-9f5d-4522-a180-9a78a8cd325e.png">

I believe that this might be due to the JSON being to large, I saw this when I opened the VSCode console:

<img width="1141" alt="Screenshot 2021-08-16 at 18 33 37" src="https://user-images.githubusercontent.com/3618384/129598133-5a4aa87a-e4e6-4074-af9d-b0dbac5a5a9b.png">

After playing around further, I ended up with this at some point:

<img width="848" alt="Screenshot 2021-08-16 at 18 26 35" src="https://user-images.githubusercontent.com/3618384/129597520-7cab0a12-f40f-45b4-854b-c743757777f5.png">

Then, the LSP stopped working altogether until I restarted VSCode and reduced the number of records. (I had like 100 with lots of syntax errors.)

**Comment by vladdeSV** [comment]
Huh, just to quickly comment on the errors failing after a while; I cannot reproduce this error. I copied your snippet and pasted repeatedly (circa 440 lines), and I do not get the same result. It runs perfectly fine for me.

![klog extension errors](https://user-images.githubusercontent.com/7542961/129602876-951e265b-091b-498b-acdf-0802b6635fe8.png)

I need to look into this a bit more. Busy now, and will get back later this week. Thank you for your thoughts!

**Comment by vladdeSV** [comment]
> there is both syntax highlighting and an LSP

Ah! That is very true. I think the syntax highlighting should be removed, even if the user does not have the `klog` binary configured, because it is inconsistent with itself when; some errors are highlighted (`asdf` and `Foo`), but not others (`h30m`, `16:00-?????????`, and `asdf15:00-?`)

Good catch!

**Comment by jotaen** [comment]
Haha, awesome font 🤠

**Comment by vladdeSV** [comment]
Inconsistent syntax highlighting fixed with #22

**Comment by vladdeSV** [comment]
> I had troubles when testing bigger files.

As I mentioned, I do not experience this on my Windows machine. I will see if I can get access to a Mac.

> Question: Why did you make the default to be “on save” and not “on edit”? I personally would always use the latter.

It is of personal preference, as I usually get stressed out when I start writing down something and directly get notified that something is wrong. I remember I was contemplated when deciding which alternative to be the default. I left it at "On save" because it felt the least "intrusive". ([relevant…](https://www.commitstrip.com/en/2020/06/11/im-watching-you/))

If you have any arguments to change it, I will gladly listen.

re: @jotaen

**Comment by jotaen** [comment]
I’ve tried again, but couldn’t reproduce the stackoverflow error in the console unfortunately

However, I consistently see that it stops reporting errors after the file reaches a certain size. The developer console stays empty.

https://user-images.githubusercontent.com/3618384/130189734-d8dc936c-66d5-4dcd-b76a-9b7c0b0f7e65.mov

That’s my config:

```
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (2 wks ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0
```

> It is of personal preference, as I usually get stressed out when I start writing down something and directly get notified that something is wrong.

Yeah, that’s a fair point, I actually don’t like that either. The downside with “on save” is that people might miss is, e.g. if they exit the editor, then it prompts “do you want to save before quitting?” and then they do “Yes”, then they won’t ever see the errors.

The only idea I can think of is to delay the errors for the current word. So if you type in something, it doesn’t show errors until you either input whitespace (which terminates the previous token), or it waits like 2 seconds or so. That’s probably a bit tricky to implement, though, so not sure it’s worth it right now.

**Comment by vladdeSV** [comment]
Just wanted to briefly mention this, because I did now know this until today; when I was testing this again on my computer, I found out my VS Code capped out at exactly 500 error messages. I checked the JSON outputted by *klog*, and it indeed outputs all errors.

However, I honestly do not think that is an issue.

**Comment by vladdeSV** [comment]
Looked a this briefly, and the JSON received caps out at 4096*2 characters. The problem lies in the extension, because running the equivalent `klog json test.klg` in the terminal gives the full, uncapped, output.

**Comment by vladdeSV** [comment]
Released. Closing.
