### ISSUE TITLE
Handle properties

### ISSUE THREAD

**Issue by vladdeSV** [vladdeSV/vscode-klog#6]
The syntax highlighter is not currently fully compliant with properties.

It only matches `(<duration>!)`, where as it should match the regex `(<property>(, <property>)+)`, where `<property>` is a defined property.

**Comment by vladdeSV** [comment]
Because *should-total* is the only defined property, it is technically compliant. Unfortunately, this will bite back when more properties are added.

**Comment by vladdeSV** [comment]
I suggest some sort of regex which matches CSV options, like `/((^|, )(<should-total>|<other-property>))/`. Just need to figure out how to write one which works well with tmLanguage.

**Comment by vladdeSV** [comment]
Also, I have no idea of how in a regex ensure a property only appears once, yet allow different properties to appear in any order.

**Comment by jotaen** [comment]
Actually, the multi properties is something I’m not sure should be included at all in the spec at this point, because there just are not more than one property at the moment. I guess in the end I had put that there as some sort of reminder for myself, because should something similar to the should-property pop up in the future (a per-record property) then it could potentially also live inside the parentheses. But who knows whether this will ever happen, plus whether it works out that way. So what that really is is premature optimisation at this point… 🤔

**Comment by vladdeSV** [comment]
Ah, that is good to know then.

I'll just keep it as it is now 👍

**Comment by jotaen** [comment]
What do you think though, whether the properties should be expressed that way in the spec at all at this point?

**Comment by vladdeSV** [comment]
To be fair, I have no real preference at all. I think that it is a bit odd that there is a whole segment to properties when there is only one property as of now. However, you decide if any new properties are added.

I have not spent quite as much time reflecting over the language, only the *structure* of the language. I think you know which is better for the language in the long run. I like it a lot because it is simple to jot down in a text file, with no complex stuff to remember.

(My own attempt at a time tracking text file at my previous job was a mix of Markdown and YAML. klog is a million times better, due to its simplicity.)

**Comment by jotaen** [comment]
It’s useful feedback anyway, and I actually wondered that no one seemed to stumble across this. I also didn’t bother to implement multi props in the CLI parser, by the way.
